---
on:
  push:
    branches:
      - tune-your-chat
  pull_request:
    branches:
      - tune-your-chat

permissions:
  contents: write

name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: build pr
        if: github.ref != 'refs/heads/tune-your-chat'
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: true
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: build and deploy
        if: github.ref == 'refs/heads/tune-your-chat'
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          PAGES_BRANCH: gh-pages
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
